//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phần_Mềm_Dinh_Dưỡng
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MonAnEntities : DbContext
    {
        public MonAnEntities()
            : base("name=MonAnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MonAn> MonAn { get; set; }
    
        public virtual ObjectResult<chon_MonAn_Result> chon_MonAn()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<chon_MonAn_Result>("chon_MonAn");
        }
    
        public virtual int sua_MonAn(Nullable<int> maMon, string tenMon, string loaiMon)
        {
            var maMonParameter = maMon.HasValue ?
                new ObjectParameter("MaMon", maMon) :
                new ObjectParameter("MaMon", typeof(int));
    
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("TenMon", tenMon) :
                new ObjectParameter("TenMon", typeof(string));
    
            var loaiMonParameter = loaiMon != null ?
                new ObjectParameter("LoaiMon", loaiMon) :
                new ObjectParameter("LoaiMon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sua_MonAn", maMonParameter, tenMonParameter, loaiMonParameter);
        }
    
        public virtual int them_MonAn(string tenMon, string loaiMon)
        {
            var tenMonParameter = tenMon != null ?
                new ObjectParameter("TenMon", tenMon) :
                new ObjectParameter("TenMon", typeof(string));
    
            var loaiMonParameter = loaiMon != null ?
                new ObjectParameter("LoaiMon", loaiMon) :
                new ObjectParameter("LoaiMon", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("them_MonAn", tenMonParameter, loaiMonParameter);
        }
    
        public virtual int xoa_MonAn(Nullable<int> maMon)
        {
            var maMonParameter = maMon.HasValue ?
                new ObjectParameter("MaMon", maMon) :
                new ObjectParameter("MaMon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("xoa_MonAn", maMonParameter);
        }
    }
}
