//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phần_Mềm_Dinh_Dưỡng
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucDon
    {
        public int Id { get; set; }
        public string NhomTre { get; set; }
        public string Thu { get; set; }
        public string Sang_MonChinh { get; set; }
        public string Sang_TrangMieng { get; set; }
        public string Trua_MonMan { get; set; }
        public string Trua_MonCanh { get; set; }
        public string Trua_MonRauCu { get; set; }
        public string Trua_TrangMieng { get; set; }
        public string Chieu_MonChinh { get; set; }
        public string Chieu_TrangMieng { get; set; }
        public string Sang_Chao { get; set; }
        public string Trua_Chao { get; set; }
        public string Trua_TrangMieng_NhaTre { get; set; }
        public string Chieu_Chao { get; set; }
        public string Chieu_TrangMieng_NhaTre { get; set; }
        public string TenThucDon { get; set; }
    
        public virtual MonAn MonAn { get; set; }
        public virtual MonAn MonAn1 { get; set; }
        public virtual MonAn MonAn2 { get; set; }
        public virtual MonAn MonAn3 { get; set; }
        public virtual MonAn MonAn4 { get; set; }
        public virtual MonAn MonAn5 { get; set; }
        public virtual MonAn MonAn6 { get; set; }
        public virtual MonAn MonAn7 { get; set; }
        public virtual MonAn MonAn8 { get; set; }
        public virtual MonAn MonAn9 { get; set; }
        public virtual MonAn MonAn10 { get; set; }
        public virtual MonAn MonAn11 { get; set; }
        public virtual MonAn MonAn12 { get; set; }
    }
}
