//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phần_Mềm_Dinh_Dưỡng
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucDonNgay
    {
        public int ID { get; set; }
        public Nullable<int> ThucDonTuanID { get; set; }
        public string Thu { get; set; }
        public string MonChinh { get; set; }
        public string MonMan { get; set; }
        public string MonCanh { get; set; }
        public string MonXao { get; set; }
        public string TrangMieng { get; set; }
    
        public virtual ThucDonTuan ThucDonTuan { get; set; }
    }
}
